"""
analyze.py
Script for loading and plotting the sensor or motor data generated by the simulation,
helping to visualize results or debug robot behavior.
"""

import numpy as np
import matplotlib.pyplot as plt


def main():
    """
    Main function to load sensor values and plot them.
    """
    target_angles_bl = np.load("./src/data/sin_values_bl.npy")
    target_angles_fl = np.load("./src/data/sin_values_fl.npy")

    plt.plot(target_angles_bl)
    plt.plot(target_angles_fl)

    plt.legend()
    plt.show()


if __name__ == "__main__":
    main()
